name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'
    
    - name: List Available Simulators
      run: xcrun simctl list devices available
    
    - name: Build Swift Package for iOS
      run: |
        swift package resolve
        # Note: Swift Package building for iOS requires Xcode project integration
        echo "Swift Package structure verified"
    
    - name: Test Swift Package Structure
      run: |
        if [ -f "Package.swift" ]; then
          echo "✅ Package.swift found"
          swift package dump-package
        else
          echo "❌ Package.swift not found"
          exit 1
        fi
    
    - name: Build iOS App
      run: |
        xcodebuild clean build \
          -project Momentum.xcodeproj \
          -target Momentum \
          -destination 'generic/platform=iOS Simulator' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
    
    - name: Build Documentation
        run: |
        swift package generate-documentation --target MomentumCore
        swift package generate-documentation --target MomentumAuthentication
        swift package generate-documentation --target MomentumUI
        swift package generate-documentation --target MomentumFeatures
    
    - name: Export Documentation Archive
      run: |
        # Swift package generate-documentation creates docs in .build/plugins/Swift-DocC/outputs/
        mkdir -p ./docs
        if [ -d ".build/plugins/Swift-DocC/outputs" ]; then
          cp -r .build/plugins/Swift-DocC/outputs/* ./docs/
        fi
    
    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./docs
        retention-days: 30
